language: R
sudo: false

cache: packages

cran: http://cran.at.r-project.org

r_github_packages:
  - jimhester/covr

before_install:
  - tlmgr install natbib

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    - NOT_CRAN: true
    - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
