language: r 

sudo: required

os:
  - linux

apt_packages:
  - latex-xcolor
  - texlive-latex3 # attempt to fix mathtools.sty not found error

r_binary_packages:
  - devtools
  - vegan
  - ggplot2
  - phangorn
  - ape
  - igraph
  - ade4
  - pegas
  - reshape2
  - dplyr
  - boot
  - shiny
  - testthat
  - knitr
  - rmarkdown
  - knitcitations
  - poweRlaw

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
notifications:
  email:
    on_success: change
    on_failure: always


env:
  global:
    - CRAN: http://cran.rstudio.com
    - NOT_CRAN: true
    - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
    - $BOOTSTRAP_LATEX="TRUE"
