language: r 

os:
  - linux

apt_packages:
  - latex-xcolor

r_packages:
  - devtools

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
    - $BOOTSTRAP_LATEX="TRUE"
